##########################################
# Base image
##########################################
FROM debian:bookworm as base
ARG DEBIAN_FRONTEND=noninteractive
##########################################
RUN apt update -y
RUN apt install -y pipewire-jack
RUN apt install -y jalv
##########################################
RUN apt install -y subversion
RUN apt install -y libxml-parser-perl
##########################################
RUN apt install -y g++ debhelper pkg-config automake libtool fakeroot libsndfile1-dev doxygen uuid-dev lv2-dev
RUN apt install -y bison libjack-jackd2-dev flex libsqlite3-dev dssi-dev
RUN apt install -y cmake
RUN apt install -y qt6-base-dev
RUN apt install -y qt6-svg-dev
RUN apt install -y qt6-tools-dev
##########################################
# Build linuxsampler components
##########################################
RUN svn co https://svn.linuxsampler.org/svn/libgig/trunk libgig
RUN svn co https://svn.linuxsampler.org/svn/linuxsampler/trunk linuxsampler
RUN svn co https://svn.linuxsampler.org/svn/liblscp/trunk liblscp
RUN svn co https://svn.linuxsampler.org/svn/qsampler/trunk qsampler
WORKDIR /libgig
RUN make -f Makefile.svn
RUN ./configure --prefix=/usr
RUN make
RUN make install
WORKDIR /linuxsampler
COPY linuxsampler-aarch64.patch .
RUN svn patch linuxsampler-aarch64.patch .
RUN make -f Makefile.svn
RUN ./configure --prefix=/usr
RUN make
RUN make install
WORKDIR /liblscp
RUN cmake -DCMAKE_INSTALL_PREFIX=/usr -B build
RUN cmake --build build
RUN cmake --install build
WORKDIR /qsampler
RUN cmake -DCMAKE_INSTALL_PREFIX=/usr -B build
RUN cmake --build build
RUN cmake --install build

##########################################
# Defult environment provided by image
##########################################
ENV LV2_PATH=/usr/lib/lv2
ENV DISPLAY=desktop:0
ENV XDG_RUNTIME_DIR=/tmp
##########################################
# Startup
##########################################
ADD entrypoint.sh /
ENTRYPOINT ["/entrypoint.sh"]


