#name: soundcan

services:

  # dela upp desktop i xserver vncserver och desktop med 1 process i varje
  desktop:
    build: desktop
    restart: unless-stopped
    ports:
      - 5900:5900
      - 6000:6000
      - 9001:9001

  tools:
    build: tools
    restart: unless-stopped
    volumes:
      - $XDG_RUNTIME_DIR/pipewire-0:/tmp/pipewire-0
      - tools-data:/tools-data
    devices:
      - /dev/snd:/dev/snd


  ui:
    build: ui
    restart: unless-stopped
    ports:
      - 9999:3300
    volumes:
      - session:/session
      - $XDG_RUNTIME_DIR/pipewire-0:/tmp/pipewire-0
    ipc: "shareable"

  fs:
    build: fluidsynth
    restart: unless-stopped
    ports:
      - 9800:9800
    volumes:
      - session:/session
      - $XDG_RUNTIME_DIR/pipewire-0:/tmp/pipewire-0
      - $PWD/store:/soundfonts

  setbfree:
    build: setbfree
    restart: unless-stopped
    volumes:
      - session:/session
      - $XDG_RUNTIME_DIR/pipewire-0:/tmp/pipewire-0
    ipc: "service:ui"

volumes:
  tools-data:
  session:
