name: sq

services:

  desktop:
    build: desktop
    restart: unless-stopped
    healthcheck:
      test: test -f /ready
    ports:
      - 5900:5900
      - 6000:6000


  tools:
    build: tools
    restart: unless-stopped
    depends_on:
      desktop:
        condition: service_healthy
    devices:
      - /dev/snd:/dev/snd
    volumes:
      - /run/user/1000/pipewire-0:/tmp/pipewire-0
      - tools-data:/tools-data


  webui:
    build: webui
    restart: unless-stopped
    ports:
      - 9999:9999


  essential-keys:
    build: essential-keys
    restart: unless-stopped
    command: pw-jack -p 128 jalv -i -H 7890 http://helander.network/lv2soundfont/EssentialKeys
    volumes:
      - /run/user/1000/pipewire-0:/tmp/pipewire-0
    ports:
      - 7890:7890

  mona-lisa:
    build: mona-lisa
    restart: unless-stopped
    command: pw-jack -p 128 jalv -i -H 7890 http://helander.network/lv2soundfont/MonaLisa
    volumes:
      - /run/user/1000/pipewire-0:/tmp/pipewire-0
    ports:
      - 7891:7890

  set-bfree:
    image: sqimage-setbfree
    restart: unless-stopped
    command: pw-jack -p 128 jalv -i -H 7890 http://gareus.org/oss/lv2/b_synth
    volumes:
      - /run/user/1000/pipewire-0:/tmp/pipewire-0
    ports:
      - 7892:7890

  setbfreecontrol:
    build: setbfreecontrol
    restart: unless-stopped
    command: pw-jack -p 128 jalv -i -H 7890 http://helander.network/plugins/lv2/setbfreecontrol
    volumes:
      - /run/user/1000/pipewire-0:/tmp/pipewire-0
    ports:
      - 7893:7890


volumes:
  tools-data:
