name: sq

services:

  desktop:
    build: desktop
    restart: unless-stopped
    healthcheck:
      test: test -f /ready
    ports:
      - 5900:5900
      - 6000:6000


  tools:
    build: tools
    restart: unless-stopped
    depends_on:
      desktop:
        condition: service_healthy
    devices:
      - /dev/snd:/dev/snd
    volumes:
      - /run/user/1000/pipewire-0:/tmp/pipewire-0
      - tools-data:/tools-data


  webui:
    build: webui
    restart: unless-stopped
    ports:
      - 9999:9999


  session:
    build: session
    restart: unless-stopped
    volumes:
      - /run/user/1000/pipewire-0:/tmp/pipewire-0
      - /home/lehswe/soundfonts/Essential-Keys-SF-v1.3.sf2:/soundfonts/essential-keys
      - /home/lehswe/soundfonts/Monalisa-GM-v2_06_5.sf2:/soundfonts/mona-lisa
    ports:
      - 7890-7892:7890-7892
#      - 5555-5556:5555-5556

  mh:
    image: sqimage-modhost
    restart: unless-stopped
    command: sleep infinity
    volumes:
      - /run/user/1000/pipewire-0:/tmp/pipewire-0
    ports:
      - 5555-5556:5555-5556


#  set-bfree:
#    image: sqimage-setbfree
#    restart: unless-stopped
#    command: pw-jack -p 128 jalv -i -H 7890 http://gareus.org/oss/lv2/b_synth
#    volumes:
#      - /run/user/1000/pipewire-0:/tmp/pipewire-0
#    ports:
#      - 7892:7890

#  setbfreecontrol:
#    build: setbfreecontrol
#    restart: unless-stopped
#    command: pw-jack -p 128 jalv -i -H 7890 http://helander.network/plugins/lv2/setbfreecontrol
#    volumes:
#      - /run/user/1000/pipewire-0:/tmp/pipewire-0
#    ports:
#      - 7893:7890


volumes:
  tools-data:
